# Generated by Django 5.0.3 on 2024-03-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('route_number', models.CharField(max_length=50)),
            ],
        ),
    ]
